#!/usr/bin/env node

'use strict'

var c = require('skilstak-colors');

 function theLord() {
   console.log(c.yellow + "ELLO JESUS! ELLO GOD!" + c.x); console.log(c.red + "and solong satin! ~ random priest" + c.x)
 }

 var disco = function () {
   console.log(c.multi("COMENCE SWEET DISCO RAVE PARTY!  ~ mettaton"));
 }

var undertale = function () {
  console.log("SANS! GET OFF MY COMPUTER!" + c.x); console.log(c.blue + "ok papayrus. ~ two cool dudes" + c.x)
}

var ILLUMINATI = function (message) {
  while (true) {
    console.log(c.g + "Message: " + message + c.x);
  }
}

//ILLUMINATI("ILLUMINATI! YOU'VE COME TO TAKE CONTROL!!!!")

 theLord();

 disco();

 undertale();
