#!/usr/bin/env python3

import skilstak.colors as c
import time



def print_foreva(who):
    while True:
        print(c.multi + "FNAF!" + who)
    
if __name__ == '__main__':
    print_foreva("FNAF!")
