#!/usr/bin/env python3

"""The Ever Glorious Hello World Program"""

def print_plain("Hello world!"):
    """Print 'Hello world!' in plain text."""
    print("Hello world!")

if __name__ == '__main__':
    print_plain("Hello world!")
