#!/usr/bin/env python3

"""The Ever So Freaking Glorious Hello World Program"""

greeting = "YO WAZZAP"

def print_plain(who):
    print(greeting + " " + who + "!")

def print_foreva(who):
    while True:
        print(greeting + " " + who + "!")

if __name__ == '__main__':
    print_foreva("world")
