#!/usr/bin/env python3

"""The Ever So Freaking Glorious Hello World Program"""

def print_plain(message):
    """Print 'Hello world!' in plain text."""
    print(message)

if __name__ == '__main__':
    print_plain("Hello world!")
